2021-11-28 23:28:23,037 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2021-11-28 23:28:23,037 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\shash\AppData\Local\Programs\Python\Python310\lib\site-packages\instabot\bot\bot.py
2021-11-28 23:28:23,038 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2021-11-28 23:28:23,355 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2021-11-28 23:28:23,643 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2021-11-28 23:28:23,943 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2021-11-28 23:28:24,253 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
2021-11-28 23:28:24,523 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [429]>
2021-11-28 23:28:24,523 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message":"Please wait a few minutes before you try again.","status":"fail"}'
2021-11-28 23:28:24,524 - instabot version: 0.117.0 (api) - ERROR - Request returns 429 error!
2021-11-28 23:28:24,524 - instabot version: 0.117.0 (api) - WARNING - That means 'too many requests'. I'll go to sleep for 5 minutes.
